name: "Feature Request"
description: "Propose a new feature or enhancement for Jaseci."
title: "[Feature]: "
labels: ["Type: Feature"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting an improvement to Jaseci!
        Please provide as much context as possible so we can evaluate and prioritize your request.
        > **Tip:** Search [existing issues](https://github.com/Jaseci-Labs/jaseci/issues) before submitting to avoid duplicates.

  - type: textarea
    id: problem
    attributes:
      label: "Problem Statement"
      description: "Is your feature request related to a problem? Describe it clearly."
      placeholder: "e.g. I find it frustrating when I have to manually re-declare types across multiple archetypes..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: "Proposed Solution"
      description: "Describe the feature or change you'd like to see."
      placeholder: "e.g. Allow archetypes to inherit type annotations from parent definitions..."
    validations:
      required: true

  - type: textarea
    id: example
    attributes:
      label: "Example / Mockup"
      description: "Provide a code snippet, pseudocode, or mockup that illustrates how this feature would work."
      placeholder: |
        ```jac
        # Example of the proposed feature
        ```
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: "Alternatives Considered"
      description: "Have you tried any workarounds or considered alternative approaches?"

  - type: dropdown
    id: area
    attributes:
      label: "Area of the Project"
      description: "Which part of Jaseci does this feature relate to?"
      options:
        - "Jac Language / Compiler"
        - "Runtime / Interpreter"
        - "Standard Library"
        - "CLI / Tooling"
        - "LSP / IDE Integration"
        - "Documentation"
        - "Other"
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: "Priority (from your perspective)"
      options:
        - "Nice to have"
        - "Important"
        - "Critical / Blocking my work"
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: "Additional Context"
      description: "Any other context, references, or related issues."

  - type: checkboxes
    id: checklist
    attributes:
      label: "Pre-submission Checklist"
      options:
        - label: "I have searched existing issues and this is not a duplicate."
          required: true
        - label: "I am willing to help implement this feature if guidance is provided."
          required: false
